### ISSUE TITLE
Stuck at block 16010533

### ISSUE THREAD

**Issue by wbelhomsi** [MetisProtocol/metis-ansible#3]
Metis node is always crashing with the same errors shown below
any idea why?
```
INFO [06-12|15:40:21.747] Running without syncing enabled
INFO [06-12|15:40:30.830] Block synchronisation started
INFO [06-12|15:40:30.830] Mining aborted due to sync
panic: Refund counter below zero (gas: 4800 > refund: 0)

goroutine 1219 [running]:
github.com/ethereum-optimism/optimism/l2geth/core/state.(*StateDB).SubRefund(0xc003a5b200, 0x12c0)
        /l2geth/core/state/statedb.go:224 +0xdc
github.com/ethereum-optimism/optimism/l2geth/core/vm.init.makeGasSStoreFunc.func12(0xc0042da008, 0xc009ad6e40, 0xc0042a8ff0, 0x10cb?, 0xc0042a8ff0?)
        /l2geth/core/vm/operations_acl.go:76 +0x53d
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc0042de008, 0xc009ad6e40, {0xc003bee584, 0x44, 0x7c}, 0x0)
        /l2geth/core/vm/interpreter.go:261 +0x86e
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc0042da008, 0xc009ad6e40, {0xc003bee584, 0x44, 0x7c}, 0x0)
        /l2geth/core/vm/evm.go:75 +0x37f
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc0042da008, {0x136a020, 0xc009ad6cc0}, {0xde, 0xad, 0xde, 0xad, 0xde, 0xad, 0xde, ...}, ...)
        /l2geth/core/vm/evm.go:256 +0x8b3
github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc0042da008?, 0xc0042de008, 0xc009ad6cc0, 0xc004d0e0a0, 0xc004c68d80)
        /l2geth/core/vm/instructions.go:771 +0x308
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc0042de008, 0xc009ad6cc0, {0xc004d3257e, 0xa4, 0x182}, 0x0)
        /l2geth/core/vm/interpreter.go:277 +0xa96
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc0042da008, 0xc009ad6cc0, {0xc004d3257e, 0xa4, 0x182}, 0x0)
        /l2geth/core/vm/evm.go:75 +0x37f
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc0042da008, {0x136a020, 0xc0000015c0}, {0xc6, 0x19, 0x5f, 0x95, 0xf4, 0xe7, 0xd9, ...}, ...)
        /l2geth/core/vm/evm.go:256 +0x8b3
github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc0042da008?, 0xc0042de008, 0xc0000015c0, 0xc003e052a0, 0xc003e54ae0)
        /l2geth/core/vm/instructions.go:771 +0x308
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc0042de008, 0xc0000015c0, {0xc0026a52c0, 0x124, 0x124}, 0x0)
        /l2geth/core/vm/interpreter.go:277 +0xa96
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc0042da008, 0xc0000015c0, {0xc0026a52c0, 0x124, 0x124}, 0x0)
        /l2geth/core/vm/evm.go:75 +0x37f
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc0042da008, {0x1369860, 0xc004042648}, {0x2d, 0x4f, 0x78, 0x8f, 0xdb, 0x26, 0x2a, ...}, ...)
        /l2geth/core/vm/evm.go:256 +0x8b3
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDbWithBlockNumber(0xc003a256c0, 0x0)
        /l2geth/core/state_transition.go:303 +0xb1b
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDb(...)
        /l2geth/core/state_transition.go:238
github.com/ethereum-optimism/optimism/l2geth/core.ApplyMessage(0x10b4dc0?, {0x1378d18?, 0xc003a5d3b0?}, 0xa8061b9b8f629c2a?)
        /l2geth/core/state_transition.go:164 +0x25
github.com/ethereum-optimism/optimism/l2geth/core.precacheTransaction(_, {_, _}, _, _, _, _, _, {0x0, {0x0, ...}, ...})
        /l2geth/core/state_prefetcher.go:83 +0x225
github.com/ethereum-optimism/optimism/l2geth/core.(*statePrefetcher).Prefetch(_, _, _, {0x0, {0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        /l2geth/core/state_prefetcher.go:64 +0x2b4
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh.func2({0xc1928e3c6cadb286?, 0x34679f383?, 0x1af6840?})
        /l2geth/core/blockchain.go:2105 +0x13c
created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh in goroutine 1073
        /l2geth/core/blockchain.go:2103 +0x1bd8
```

**Comment by ericlee42** [comment]
> You can add --cache.noprefetch=true argument to your l2geth service

**Comment by Zorato** [comment]
My node has recoverd and syncning again after adding this flag, but now I get lots of 
```
ERROR[06-18|10:57:30.124] Get sequencer error when GetEpochByBlock err="execution reverted"
ERROR[06-18|10:57:30.124] GetTxSequencer                           err="execution reverted"
ERROR[06-18|10:57:30.124] HandleSyncFromOther applyTransaction     tx=6072d7…85e97a err="execution reverted"
```
errors in my log. 
Is this something I should be worried about? Is my blockchain data consistent and aligned with the one in the actual chain?

**Comment by ericlee42** [comment]
> My node has recoverd and syncning again after adding this flag, but now I get lots of

Seems that your l2geth doesn't use 8545 as the rpc port.

You should update the configuration.

**Comment by ericlee42** [comment]
Please file a new issue.
