### ISSUE TITLE
ERROR's: element not found, concurrent map read and map write, failed to meet quorum

### ISSUE THREAD

**Issue by JuManjey** [MetisProtocol/metis-ansible#8]
```
dtl = "v0.1.2"
l2geth = "v0.2.4"
GCMODE: "full"
SYNCMODE: "full"
DATA_TRANSPORT_LAYER__SYNC_L1_BATCH: "true"
```
**l2geth:**
```
ERROR[06-24|21:45:11.961] handler blocksBeforeInsert get equeue    err="element not found"
WARN [06-24|21:45:11.961] Synchronisation failed, retrying         err="element not found"
ERROR[06-24|21:45:16.844] handler blocksBeforeInsert get equeue    err="element not found"
WARN [06-24|21:45:16.844] Synchronisation failed, retrying         err="element not found"
ERROR[06-24|21:45:47.955] handler blocksBeforeInsert get equeue    err="element not found"
WARN [06-24|21:45:47.955] Synchronisation failed, retrying         err="element not found"
ERROR[06-24|21:46:15.591] handler blocksBeforeInsert get equeue    err="element not found"
```
**l1dtl with that:**
```
251000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000653a729800000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000084704316e500000000000000000000000000000000000000000000000000000000000000a762239a8bd4b261711795f0342e826a8508385df165419149f3ff4d30918a62e5000000000000000000000000000000000000000000000000000000000000000a62239a8bd4b261711795f0342e826a8508385df165419149f3ff4d30918a62e50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000824f7369942c72a085af05c568961f5efb435c71fb6a842056a01b10e87086ce472d9de004abadcd571c76316e56c4bd9c3bf07e5b525af4060aa66780d0ae1aef1cef5496a28c9e3d2e2c76c66cdafb24a6e41596200d7ee0d77698151de7349ba351f6d0b28c1ba8f681df2879bca15f0abc9b9c4703a89ee2b43f32f790e8d92e1b000000000000000000000000000000000000000000000000000000000000","sig":{"v":1,"r":"0xfaa8b1ae07705866b156e379c199e0877f7e8cb82a634c742f6c68c5cd8f63e7","s":"0x3d6ae634799fba96a01f198d24778ef8a187e8eb8d31c4db4f9adf4b53633626"}},"confirmed":true,"seqSign":null},{"index":9086612,"batchIndex":38823,"blockNumber":18433086,"timestamp":1698307640,"gasLimit":"0","target":"0x0000000000000000000000000000000000000000","origin":null,"data":"0xf8af8303403c8503d77a05008317cdc094c635f3b04276a0fed51f8995b94440d3202c8c7a80b84417835d1c0000000000000000000000000000000000014813000037b4001c62aa0211863b00000000000000000000000000000000000000000000000000000000653a1e618208a4a0a1a13e5e42ed4f5370884c852db504c34b0ab95b279276e226b691f34917c3c2a01880d96250e59f3346499f0bd130550fcfb682aab35ad3a2cfa21eea7dd6ccfb","queueOrigin":"sequencer","value":"0x0","queueIndex":null,"decoded":{"nonce":"213052","gasPrice":"16500000000","gasLimit":"1560000","value":"0x0","target":"0xc635f3b04276a0fed51f8995b94440d3202c8c7a","data":"0x17835d1c0000000000000000000000000000000000014813000037b4001c62aa0211863b00000000000000000000000000000000000000000000000000000000653a1e61","sig":{"v":1,"r":"0xa1a13e5e42ed4f5370884c852db504c34b0ab95b279276e226b691f34917c3c2","s":"0x1880d96250e59f3346499f0bd130550fcfb682aab35ad3a2cfa21eea7dd6ccfb"}},"confirmed":true,"seqSign":null}]},"msg":"Storing Event:"}
{"level":30,"time":1719268328516,"eventName":"SequencerBatchAppended","numEvents":4,"durationMs":9529,"msg":"Processed events"}
{"level":30,"time":1719268328564,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1719268328564,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18433200, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1719268328666,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1719268328666,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18433200, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1719268328806,"chainId":1088,"parsedEvent":{"index":38820,"chainId":1088,"batchIndex":38820,"shouldStartAtElement":9083906,"totalElementsToAppend":432,"txBatchSize":418282,"txBatchTime":1698296621589,"root":"0x6a8a803fcc2ce570334df2b7b50e2f644459e995b30af911554a1345ab01a20d","l1BlockNumber":18432207,"timestamp":1698296879},"msg":"Storing Event:"}
{"level":30,"time":1719268328870,"chainId":1088,"parsedEvent":{"index":38821,"chainId":1088,"batchIndex":38821,"shouldStartAtElement":9084338,"totalElementsToAppend":712,"txBatchSize":656704,"txBatchTime":1698300365161,"root":"0x28dd365426b5916f3be8928c69909d5f41a2843eae06ab572219fc1d88286169","l1BlockNumber":18432495,"timestamp":1698300371},"msg":"Storing Event:"}
{"level":30,"time":1719268328934,"chainId":1088,"parsedEvent":{"index":38822,"chainId":1088,"batchIndex":38822,"shouldStartAtElement":9085050,"totalElementsToAppend":654,"txBatchSize":619966,"txBatchTime":1698303975513,"root":"0xd911611e50a464dd217e5e88d32541f6edfee5b642c3d78a640078c3ab97db1d","l1BlockNumber":18432797,"timestamp":1698304007},"msg":"Storing Event:"}
{"level":30,"time":1719268328983,"chainId":1088,"parsedEvent":{"index":38823,"chainId":1088,"batchIndex":38823,"shouldStartAtElement":9085704,"totalElementsToAppend":909,"txBatchSize":844954,"txBatchTime":1698307715654,"root":"0xca227fcb0ba819022e315d4476aada9b06460d6896cbfc6dcb8006d4ff33e86e","l1BlockNumber":18433107,"timestamp":1698307739},"msg":"Storing Event:"}
{"level":30,"time":1719268328984,"eventName":"AppendBatchElement","numEvents":4,"durationMs":240,"msg":"Processed events"}251000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000653a729800000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000084704316e500000000000000000000000000000000000000000000000000000000000000a762239a8bd4b261711795f0342e826a8508385df165419149f3ff4d30918a62e5000000000000000000000000000000000000000000000000000000000000000a62239a8bd4b261711795f0342e826a8508385df165419149f3ff4d30918a62e50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000824f7369942c72a085af05c568961f5efb435c71fb6a842056a01b10e87086ce472d9de004abadcd571c76316e56c4bd9c3bf07e5b525af4060aa66780d0ae1aef1cef5496a28c9e3d2e2c76c66cdafb24a6e41596200d7ee0d77698151de7349ba351f6d0b28c1ba8f681df2879bca15f0abc9b9c4703a89ee2b43f32f790e8d92e1b000000000000000000000000000000000000000000000000000000000000","sig":{"v":1,"r":"0xfaa8b1ae07705866b156e379c199e0877f7e8cb82a634c742f6c68c5cd8f63e7","s":"0x3d6ae634799fba96a01f198d24778ef8a187e8eb8d31c4db4f9adf4b53633626"}},"confirmed":true,"seqSign":null},{"index":9086612,"batchIndex":38823,"blockNumber":18433086,"timestamp":1698307640,"gasLimit":"0","target":"0x0000000000000000000000000000000000000000","origin":null,"data":"0xf8af8303403c8503d77a05008317cdc094c635f3b04276a0fed51f8995b94440d3202c8c7a80b84417835d1c0000000000000000000000000000000000014813000037b4001c62aa0211863b00000000000000000000000000000000000000000000000000000000653a1e618208a4a0a1a13e5e42ed4f5370884c852db504c34b0ab95b279276e226b691f34917c3c2a01880d96250e59f3346499f0bd130550fcfb682aab35ad3a2cfa21eea7dd6ccfb","queueOrigin":"sequencer","value":"0x0","queueIndex":null,"decoded":{"nonce":"213052","gasPrice":"16500000000","gasLimit":"1560000","value":"0x0","target":"0xc635f3b04276a0fed51f8995b94440d3202c8c7a","data":"0x17835d1c0000000000000000000000000000000000014813000037b4001c62aa0211863b00000000000000000000000000000000000000000000000000000000653a1e61","sig":{"v":1,"r":"0xa1a13e5e42ed4f5370884c852db504c34b0ab95b279276e226b691f34917c3c2","s":"0x1880d96250e59f3346499f0bd130550fcfb682aab35ad3a2cfa21eea7dd6ccfb"}},"confirmed":true,"seqSign":null}]},"msg":"Storing Event:"}
{"level":30,"time":1719268328516,"eventName":"SequencerBatchAppended","numEvents":4,"durationMs":9529,"msg":"Processed events"}
{"level":30,"time":1719268328564,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1719268328564,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18433200, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1719268328666,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1719268328666,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18433200, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1719268328806,"chainId":1088,"parsedEvent":{"index":38820,"chainId":1088,"batchIndex":38820,"shouldStartAtElement":9083906,"totalElementsToAppend":432,"txBatchSize":418282,"txBatchTime":1698296621589,"root":"0x6a8a803fcc2ce570334df2b7b50e2f644459e995b30af911554a1345ab01a20d","l1BlockNumber":18432207,"timestamp":1698296879},"msg":"Storing Event:"}
{"level":30,"time":1719268328870,"chainId":1088,"parsedEvent":{"index":38821,"chainId":1088,"batchIndex":38821,"shouldStartAtElement":9084338,"totalElementsToAppend":712,"txBatchSize":656704,"txBatchTime":1698300365161,"root":"0x28dd365426b5916f3be8928c69909d5f41a2843eae06ab572219fc1d88286169","l1BlockNumber":18432495,"timestamp":1698300371},"msg":"Storing Event:"}
{"level":30,"time":1719268328934,"chainId":1088,"parsedEvent":{"index":38822,"chainId":1088,"batchIndex":38822,"shouldStartAtElement":9085050,"totalElementsToAppend":654,"txBatchSize":619966,"txBatchTime":1698303975513,"root":"0xd911611e50a464dd217e5e88d32541f6edfee5b642c3d78a640078c3ab97db1d","l1BlockNumber":18432797,"timestamp":1698304007},"msg":"Storing Event:"}
{"level":30,"time":1719268328983,"chainId":1088,"parsedEvent":{"index":38823,"chainId":1088,"batchIndex":38823,"shouldStartAtElement":9085704,"totalElementsToAppend":909,"txBatchSize":844954,"txBatchTime":1698307715654,"root":"0xca227fcb0ba819022e315d4476aada9b06460d6896cbfc6dcb8006d4ff33e86e","l1BlockNumber":18433107,"timestamp":1698307739},"msg":"Storing Event:"}
{"level":30,"time":1719268328984,"eventName":"AppendBatchElement","numEvents":4,"durationMs":240,"msg":"Processed events"}
```

**After that I change GCMODE to archive:**
```
dtl = "v0.1.2"
l2geth = "v0.2.4"
GCMODE: "archive"
SYNCMODE: "full"
DATA_TRANSPORT_LAYER__SYNC_L1_BATCH: "true"
```
**l2geth:**
```
INFO [06-26|02:38:19.604] applyTransaction                         tx=0x43d8af76abc98615ae7677724af1f27d3716d54b6ac7919776f245f4c5757d3b fromLocal=false
INFO [06-26|02:38:19.604] start to applyTransaction                tx=0xaf4dc4274cfce5014b2a6d3690ad83811e27b9fe39e58331e00d9f817667cc69
INFO [06-26|02:38:19.604] applyTransaction                         tx=0xaf4dc4274cfce5014b2a6d3690ad83811e27b9fe39e58331e00d9f817667cc69 fromLocal=false
fatal error: concurrent map read and map write

goroutine 118 [running]:
github.com/ethereum-optimism/optimism/l2geth/rlp.cachedTypeInfo1({0x137f268, 0xf03a20}, {0x4?, 0x9?, 0x68?, 0xf2?})
	/l2geth/rlp/typecache.go:92 +0x7f
github.com/ethereum-optimism/optimism/l2geth/rlp.structFields({0x137f268, 0x1092fc0})
	/l2geth/rlp/typecache.go:122 +0x18a
```
....
```
INFO [06-26|02:38:43.314] Running without syncing enabled 
INFO [06-26|02:38:52.724] Block synchronisation started 
INFO [06-26|02:38:52.724] Mining aborted due to sync 
WARN [06-26|02:38:54.714] Synchronisation failed, dropping peer    peer=64237bc7c0917e2d err="retrieved hash chain is invalid"
WARN [06-26|02:38:57.227] Synchronisation failed, dropping peer    peer=9839fd6d79a1ee73 err="retrieved hash chain is invalid"
WARN [06-26|02:39:04.789] Synchronisation failed, dropping peer    peer=b002da50837ea9f9 err="retrieved hash chain is invalid"
INFO [06-26|02:39:12.647] New local node record                    seq=44 id=5b5107d34d357f5e ip=51.161.116.4 udp=30303 tcp=30303
WARN [06-26|02:39:17.171] Synchronisation failed, dropping peer    peer=d3f38b581c707bf9 err="retrieved hash chain is invalid"
WARN [06-26|02:39:20.151] Synchronisation failed, dropping peer    peer=4e3b95932f4b7754 err="retrieved hash chain is invalid"
```

And with that I get "`panic: Refund counter below zero (gas: 4800 > refund: 0`". To resolve this I add "`--cache.noprefetch`". 
Everything was working fine, and the node was almost synchronized, but errors started appearing during proper synchronization.
```
dtl = "v0.1.2"
l2geth = "v0.2.4"
gcmode = archive
syncmode = full
--cache.noprefetch=true
DATA_TRANSPORT_LAYER__SYNC_L1_BATCH: "true"
```
**First errors:**
```
...
2024-06-27 20:07:51.634	
INFO [06-27|17:07:51.634] start to applyTransaction                tx=0xad82b97224cb52534c5565d5e6eb729fde7e7eeeb16ae22c081be11d0858a003
2024-06-27 20:07:51.634	
INFO [06-27|17:07:51.634] applyTransaction                         tx=0xad82b97224cb52534c5565d5e6eb729fde7e7eeeb16ae22c081be11d0858a003 fromLocal=false
2024-06-27 20:07:51.634	
INFO [06-27|17:07:51.634] sync from other node                     index=15214511 hash=0xad82b97224cb52534c5565d5e6eb729fde7e7eeeb16ae22c081be11d0858a003
2024-06-27 20:07:51.634	
INFO [06-27|17:07:51.634] sync from other node applyTransactionToTip finish current latest=15214511
2024-06-27 20:08:09.995	
ERROR[06-27|17:08:09.995] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:08:09.995	
WARN [06-27|17:08:09.995] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:08:32.327	
INFO [06-27|17:08:32.327] Deep froze chain segment                 blocks=633   elapsed=346.949ms number=15124511 hash=43865a…7872f7
2024-06-27 20:08:35.196	
ERROR[06-27|17:08:35.196] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:08:35.196	
WARN [06-27|17:08:35.196] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:08:38.642	
INFO [06-27|17:08:38.641] Imported new chain segment               blocks=2     txs=2    mgas=0.295    elapsed=5.086ms   mgasps=58.043  number=15214514 hash=52799e…350d28 age=3mo2w1d    dirty=0.00B
2024-06-27 20:08:38.642	
INFO [06-27|17:08:38.641] handle blocks inerted of fetcher or downloader len=2
2024-06-27 20:08:38.642	
INFO [06-27|17:08:38.642] start to applyTransaction                tx=0xb1ee51918f3e59f96f16354b87dfcf859117c520bbbc9e51abf965ba730cfdd9
2024-06-27 20:08:38.642	
INFO [06-27|17:08:38.642] applyTransaction                         tx=0xb1ee51918f3e59f96f16354b87dfcf859117c520bbbc9e51abf965ba730cfdd9 fromLocal=false
2024-06-27 20:08:38.642	
INFO [06-27|17:08:38.642] sync from other node                     index=15214512 hash=0xb1ee51918f3e59f96f16354b87dfcf859117c520bbbc9e51abf965ba730cfdd9
...
```
**and again**
```
....
2024-06-27 20:08:38.727	
INFO [06-27|17:08:38.727] start to applyTransaction                tx=0x1538d00e43e14e1910fc408936124049d8d02a43ddd174a5702b649cf2cb1f87
2024-06-27 20:08:38.727	
INFO [06-27|17:08:38.727] applyTransaction                         tx=0x1538d00e43e14e1910fc408936124049d8d02a43ddd174a5702b649cf2cb1f87 fromLocal=false
2024-06-27 20:08:38.727	
INFO [06-27|17:08:38.727] sync from other node                     index=15214521 hash=0x1538d00e43e14e1910fc408936124049d8d02a43ddd174a5702b649cf2cb1f87
2024-06-27 20:08:38.727	
INFO [06-27|17:08:38.727] sync from other node applyTransactionToTip finish current latest=15214521
2024-06-27 20:08:39.269	
ERROR[06-27|17:08:39.269] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:08:39.269	
WARN [06-27|17:08:39.269] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] Imported new chain segment               blocks=8     txs=8    mgas=0.798    elapsed=16.452ms  mgasps=48.512  number=15214530 hash=6d42e5…1a1ec7 age=3mo2w1d    dirty=0.00B
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] handle blocks inerted of fetcher or downloader len=8
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] start to applyTransaction                tx=0x5173441b803a2447fa508dbd9ddca34a1f7b7f53af3acd07de500f18802dde7c
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] applyTransaction                         tx=0x5173441b803a2447fa508dbd9ddca34a1f7b7f53af3acd07de500f18802dde7c fromLocal=false
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] sync from other node                     index=15214522 hash=0x5173441b803a2447fa508dbd9ddca34a1f7b7f53af3acd07de500f18802dde7c
2024-06-27 20:08:49.147	
INFO [06-27|17:08:49.147] sync from other node applyTransactionToTip finish current latest=15214522
...
```
**The error started appearing more and more frequently, and it ended with these logs.**
```
2024-06-27 20:10:05.041	
INFO [06-27|17:10:05.041] applyTransaction                         tx=0xbb61651b564343057750450c196a682569120ceed9b6a0095db5a13ddf69d7c1 fromLocal=false
2024-06-27 20:10:05.042	
INFO [06-27|17:10:05.041] sync from other node                     index=15214537 hash=0xbb61651b564343057750450c196a682569120ceed9b6a0095db5a13ddf69d7c1
2024-06-27 20:10:05.042	
INFO [06-27|17:10:05.041] sync from other node applyTransactionToTip finish current latest=15214537
2024-06-27 20:10:25.050	
ERROR[06-27|17:10:25.050] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:10:25.050	
WARN [06-27|17:10:25.050] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:10:30.747	
ERROR[06-27|17:10:30.747] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:10:30.760	
WARN [06-27|17:10:30.760] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:10:32.692	
INFO [06-27|17:10:32.692] Deep froze chain segment                 blocks=2     elapsed=163.854ms number=15124537 hash=e57655…ba2bba
2024-06-27 20:10:52.259	
ERROR[06-27|17:10:52.259] handler blocksBeforeInsert get equeue    err="element not found"
2024-06-27 20:10:52.259	
WARN [06-27|17:10:52.259] Synchronisation failed, retrying         err="element not found"
2024-06-27 20:11:21.675	
ERROR[06-27|17:11:21.674] handler blocksBeforeInsert get equeue    err="element not found"
```
And with that I have:
`Error: failed to meet quorum`

To resolve this I change some env values:
```
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=100
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=15000
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=100
```
**Last logs.**
**l1dtl:**
```
{"level":30,"time":1720116329610,"msg":"Read cached contract address for CanonicalTransactionChain from 0 to 18082800, get 0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9"}
{"level":30,"time":1720116329732,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1720116329732,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18082800, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1720116329848,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1720116329848,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18082800, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1720116339924,"fromL1Block":18082700,"toL1Block":18082800,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1720116339987,"msg":"Reading from local StateCommitmentChain, chainId is 1"}
{"level":30,"time":1720116339987,"msg":"Read cached contract address for StateCommitmentChain from 0 to 18082800, get 0xf209815E595Cdf3ed0aAF9665b1772e608AB9380"}
{"level":30,"time":1720116340100,"usingL2ChainId":1088,"latestBatch":{"index":37651,"root":"0x15a2f42e0ce078d5f99500c8dbb48d36828b973cc26a9698e85d3034ee7eb45f","size":541,"prevTotalElements":8449219,"extraData":"0x","blockNumber":18082618,"timestamp":1694066315,"submitter":"0xcDf02971871B7736874E20B8487c019D28090019","l1TransactionHash":"0xcefc26a4ef7f7272f8d491082c39d6ebae7754bb6e872addb1d49d935a543e05"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720116340100,"highestSyncedL1Block":18082800,"targetL1Block":18082900,"highestSyncedL1BatchIndex":37651,"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720116340163,"msg":"Reading from local CanonicalTransactionChain, chainId is 1"}
{"level":30,"time":1720116340163,"msg":"Read cached contract address for CanonicalTransactionChain from 0 to 18082900, get 0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9"}
{"level":30,"time":1720116340235,"chainId":1088,"parsedEvent":{"index":28234,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece900000000000000000000000042000000000000000000000000000000000000100000000000000000000000003980c9ed79d2c191a89e02fa3529c60ed6e9c04b00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000006e4a00000000000000000000000000000000000000000000000000000000000000e4662a633a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddead000000000000000000000000000092ee18538c392361f1923794aa62bd3a6550c8b100000000000000000000000092ee18538c392361f1923794aa62bd3a6550c8b100000000000000000000000000000000000000000000000005ff7ee708bce80000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","gasLimit":"200000","origin":"0x192E1101855bD523Ba69a9794e0217f0Db633510","blockNumber":18082890,"timestamp":1720116340,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1720116340235,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":0,"msg":"Processed events"}
{"level":30,"time":1720116340290,"msg":"Reading from local CanonicalTransactionChain, chainId is 1"}
{"level":30,"time":1720116340290,"msg":"Read cached contract address for CanonicalTransactionChain from 0 to 18082900, get 0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9"}
{"level":30,"time":1720116340411,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1720116340411,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18082900, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
{"level":30,"time":1720116340554,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
{"level":30,"time":1720116340554,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 18082900, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
```

**l2geth:**
```
ERROR[07-04|18:04:41.077] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:04:41.078] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:04:55.510] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:04:55.510] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:03.840] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:03.840] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:15.839] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:15.839] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:18.755] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:18.755] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:28.646] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:28.646] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:39.465] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:39.465] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:05:57.334] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:05:57.334] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:06:01.330] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:06:01.331] Synchronisation failed, retrying         err="element not found"
ERROR[07-04|18:06:17.315] handler blocksBeforeInsert get equeue    err="element not found"
WARN [07-04|18:06:17.315] Synchronisation failed, retrying         err="element not found"
```

Please pay attention to these errors and advise on which specific settings need to be used for the successful and stable operation of the node. These issues are not only affecting me. I am collaborating with other validators, and they are in a similar situation. Thank you for your attention.

**Comment by ericlee42** [comment]
It means your l1dtl is syncing, you can just wait for its complete.
