### ISSUE TITLE
Sepolia DTL can't sync

### ISSUE THREAD

**Issue by hdiass** [MetisProtocol/metis-ansible#9]
I'm trying to sync sepolia and always end up stuck in this bit on dtl

Using dtl 0.1.2 and l2geth 0.2.4

```
{"level":30,"time":1720170576205,"msg":"Service L1_Data_Transport_Service is starting..."}
{"level":30,"time":1720170576206,"msg":"Service L1_Data_Transport_Service is initializing..."}
{"level":30,"time":1720170576206,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1720170576222,"msg":"Service L1_Transport_Server is initializing..."}
{"level":30,"time":1720170576229,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
{"level":30,"time":1720170576229,"url":"eth-sepolia-url","msg":"HTTP Server L1 RPC Provider initialized"}
{"level":40,"time":1720170576229,"msg":"HTTP Server L2 RPC Provider not initialized"}
{"level":30,"time":1720170576229,"msg":"Service L1_Transport_Server has initialized."}
{"level":30,"time":1720170576229,"msg":"Service L1_Ingestion_Service is initializing..."}
{"level":30,"time":1720170576282,"addressManager":"0xa66Fa1eD0f1C1ee300893B4eb5493FeAD9a7e9c3","msg":"Using AddressManager"}
{"level":30,"time":1720170576724,"startingL1BlockNumber":5375027,"msg":"Starting sync"}
{"level":30,"time":1720170576758,"msg":"Service L1_Ingestion_Service has initialized."}
{"level":30,"time":1720170576759,"msg":"Service L1_Data_Transport_Service has initialized."}
{"level":30,"time":1720170576759,"msg":"Service L1_Transport_Server is starting..."}
{"level":30,"time":1720170576759,"msg":"Service L1_Ingestion_Service is starting..."}
{"level":30,"time":1720170576760,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
{"level":30,"time":1720170576760,"msg":"Service L1_Transport_Server can stop now"}
{"level":30,"time":1720170576996,"usingL2ChainId":59902,"latestBatch":{"index":2071,"root":"0xcab168f2d7659ac0b890ebbe9a3785687043e403dbf2e1ae49fb2e47f43b0a64","size":783,"prevTotalElements":784417,"extraData":"","blockNumber":5845801,"timestamp":1714964172,"submitter":"0x578c88EeEe23Db03E70aDB2445F0043bEC3C416E","l1TransactionHash":"0xc4906c89f3f14ce8b917cd7119de6c28b80d85d77c457f8d61a8911b6ae86667"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170576996,"highestSyncedL1Block":5845827,"targetL1Block":5846027,"highestSyncedL1BatchIndex":2071,"inboxAddress":"0xff00000000000000000000000001115511159902","inboxSender":"0x578c88eeee23db03e70adb2445f0043bec3c416e","inboxBatchStart":1,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170577041,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170578135,"chainId":59902,"parsedEvent":{"index":1725,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece900000000000000000000000042000000000000000000000000000000000000100000000000000000000000009848de505e6aa301ceecfcf23a0a150140fc996e000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000006bd00000000000000000000000000000000000000000000000000000000000000e4662a633a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddead00000000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc60000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc600000000000000000000000000000000000000000000000006f05b59d3b2000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","gasLimit":"200000","origin":"0x5653C621EeE9fC533C2E6Bd80880C89990Ee21dE","blockNumber":5845919,"timestamp":1714965720,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1720170578138,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":3,"msg":"Processed events"}
{"level":30,"time":1720170578192,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170579560,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170580513,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170609836,"fromL1Block":5845827,"toL1Block":5846027,"msg":"_syncInboxBatch get blocks"}
read object err The specified key does not exist.
read object err The specified key does not exist.
read object err The specified key does not exist.
{"level":50,"time":1720170617666,"extra":{"message":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3","stack":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3\n    at Object.parseEvent (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-inbox.ts:127:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncInboxBatch (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:528:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:362:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:149:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1720170632711,"usingL2ChainId":59902,"latestBatch":{"index":2071,"root":"0xcab168f2d7659ac0b890ebbe9a3785687043e403dbf2e1ae49fb2e47f43b0a64","size":783,"prevTotalElements":784417,"extraData":"","blockNumber":5845801,"timestamp":1714964172,"submitter":"0x578c88EeEe23Db03E70aDB2445F0043bEC3C416E","l1TransactionHash":"0xc4906c89f3f14ce8b917cd7119de6c28b80d85d77c457f8d61a8911b6ae86667"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170632711,"highestSyncedL1Block":5845827,"targetL1Block":5846027,"highestSyncedL1BatchIndex":2071,"inboxAddress":"0xff00000000000000000000000001115511159902","inboxSender":"0x578c88eeee23db03e70adb2445f0043bec3c416e","inboxBatchStart":1,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170632737,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170633748,"chainId":59902,"parsedEvent":{"index":1725,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece900000000000000000000000042000000000000000000000000000000000000100000000000000000000000009848de505e6aa301ceecfcf23a0a150140fc996e000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000006bd00000000000000000000000000000000000000000000000000000000000000e4662a633a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddead00000000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc60000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc600000000000000000000000000000000000000000000000006f05b59d3b2000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","gasLimit":"200000","origin":"0x5653C621EeE9fC533C2E6Bd80880C89990Ee21dE","blockNumber":5845919,"timestamp":1714965720,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1720170633749,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":2,"msg":"Processed events"}
{"level":30,"time":1720170633797,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170634881,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170636207,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170664134,"fromL1Block":5845827,"toL1Block":5846027,"msg":"_syncInboxBatch get blocks"}
read object err The specified key does not exist.
read object err The specified key does not exist.
read object err The specified key does not exist.
{"level":50,"time":1720170669882,"extra":{"message":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3","stack":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3\n    at Object.parseEvent (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-inbox.ts:127:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncInboxBatch (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:528:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:362:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:149:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1720170684935,"usingL2ChainId":59902,"latestBatch":{"index":2071,"root":"0xcab168f2d7659ac0b890ebbe9a3785687043e403dbf2e1ae49fb2e47f43b0a64","size":783,"prevTotalElements":784417,"extraData":"","blockNumber":5845801,"timestamp":1714964172,"submitter":"0x578c88EeEe23Db03E70aDB2445F0043bEC3C416E","l1TransactionHash":"0xc4906c89f3f14ce8b917cd7119de6c28b80d85d77c457f8d61a8911b6ae86667"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170684935,"highestSyncedL1Block":5845827,"targetL1Block":5846027,"highestSyncedL1BatchIndex":2071,"inboxAddress":"0xff00000000000000000000000001115511159902","inboxSender":"0x578c88eeee23db03e70adb2445f0043bec3c416e","inboxBatchStart":1,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170684975,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170686113,"chainId":59902,"parsedEvent":{"index":1725,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece900000000000000000000000042000000000000000000000000000000000000100000000000000000000000009848de505e6aa301ceecfcf23a0a150140fc996e000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000006bd00000000000000000000000000000000000000000000000000000000000000e4662a633a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddead00000000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc60000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc600000000000000000000000000000000000000000000000006f05b59d3b2000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","gasLimit":"200000","origin":"0x5653C621EeE9fC533C2E6Bd80880C89990Ee21dE","blockNumber":5845919,"timestamp":1714965720,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1720170686115,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":2,"msg":"Processed events"}
{"level":30,"time":1720170686176,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170687242,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170688399,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170717962,"fromL1Block":5845827,"toL1Block":5846027,"msg":"_syncInboxBatch get blocks"}
read object err The specified key does not exist.
read object err The specified key does not exist.
read object err The specified key does not exist.
{"level":50,"time":1720170725328,"extra":{"message":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3","stack":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3\n    at Object.parseEvent (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-inbox.ts:127:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncInboxBatch (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:528:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:362:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:149:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1720170740648,"usingL2ChainId":59902,"latestBatch":{"index":2071,"root":"0xcab168f2d7659ac0b890ebbe9a3785687043e403dbf2e1ae49fb2e47f43b0a64","size":783,"prevTotalElements":784417,"extraData":"","blockNumber":5845801,"timestamp":1714964172,"submitter":"0x578c88EeEe23Db03E70aDB2445F0043bEC3C416E","l1TransactionHash":"0xc4906c89f3f14ce8b917cd7119de6c28b80d85d77c457f8d61a8911b6ae86667"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170740648,"highestSyncedL1Block":5845827,"targetL1Block":5846027,"highestSyncedL1BatchIndex":2071,"inboxAddress":"0xff00000000000000000000000001115511159902","inboxSender":"0x578c88eeee23db03e70adb2445f0043bec3c416e","inboxBatchStart":1,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1720170740693,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170741736,"chainId":59902,"parsedEvent":{"index":1725,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece900000000000000000000000042000000000000000000000000000000000000100000000000000000000000009848de505e6aa301ceecfcf23a0a150140fc996e000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000006bd00000000000000000000000000000000000000000000000000000000000000e4662a633a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000deaddeaddeaddeaddeaddeaddeaddeaddead00000000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc60000000000000000000000000812b871c513ba29d971ccdbce8a1a1e04e56dc600000000000000000000000000000000000000000000000006f05b59d3b2000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","gasLimit":"200000","origin":"0x5653C621EeE9fC533C2E6Bd80880C89990Ee21dE","blockNumber":5845919,"timestamp":1714965720,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1720170741738,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":2,"msg":"Processed events"}
{"level":30,"time":1720170741776,"msg":"Searching from RPC CanonicalTransactionChain"}
{"level":30,"time":1720170742842,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170743819,"msg":"Searching from RPC Proxy__MVM_CanonicalTransaction"}
{"level":30,"time":1720170772852,"fromL1Block":5845827,"toL1Block":5846027,"msg":"_syncInboxBatch get blocks"}
read object err The specified key does not exist.
read object err The specified key does not exist.
read object err The specified key does not exist.
{"level":50,"time":1720170777779,"extra":{"message":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3","stack":"Error: Read data from minio failed, object is 0018f4bd551740000018cc03ab6ecadcd6d7bd03a6a6e69a45abcd8214738a06733187d85d922628d19fc3\n    at Object.parseEvent (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-inbox.ts:127:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncInboxBatch (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:528:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:362:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:149:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)"},"msg":"Caught an unhandled error"}

```

**Comment by hdiass** [comment]
Can you please assist @ericlee42 ?

**Comment by hdiass** [comment]
I have 2 nodes and they get this issue in same blocks

**Comment by hdiass** [comment]
Error on l2geth 
```
ERROR[07-05|11:48:17.584] Verify block with seqset                 block=751722 err="incorrect sequencer"
```

**Comment by hdiass** [comment]
Sorted with l2geth 0.2.0, so there must be a bug for sure
